# Annotation of Thalassiosirales transcriptomes using Dammit and eggNOG-mapper.
# Requirements:
# diamond-2.0.8, dammit 1.2, eggnog-mapper-2.0.1 

# .pep files generated by transdecoder.Predict must be in working directory


# eggNOG-mapper annotation
for file in *.pep
do
out=${file/-Trinity.fasta.transdecoder.pep/emapper}
emapper.py -i ${file} -m diamond --output ${out} --evalue 0.00001
done


# dammit annotation

for file in *.pep
do
dammit annotate ${file} --busco-group eukaryota --n_threads 8
done
